SELECT
    LA.DISTRICT_CODE CODE,
    D.DISTRICT_NAME NAME,
    LA.LATITUDE LAT,
    LA.LONGITUDE LON
FROM LOCATION_TBL LA
CROSS JOIN(
    SELECT *
    FROM LOCATION_TBL
    WHERE DISTRICT_CODE = '1101'
) LB
INNER JOIN DISTRICT D
ON LA.DISTRICT_CODE = D.DISTRICT_CODE
WHERE LA.DISTRICT_CODE <> '1101'
ORDER BY (
    POW((LA.LATITUDE - LB.LATITUDE), 2) + POW((LA.LONGITUDE - LB.LONGITUDE), 2)
) DESC, LA.DISTRICT_CODE;
