SELECT
    S.PF_CODE CODE,
    P.PF_NAME NAME,
    ROUND((CAST(PROMOTE_MUNICIPALITY AS REAL)/ CAST(MUNICIPALITY_TTL AS REAL)) * 100, 2) RATIO
FROM SDGS S
LEFT OUTER JOIN PREFECTURE P
ON S.PF_CODE = P.PF_CODE
WHERE SURVEY_YEAR = '2022'
ORDER BY RATIO DESC, S.PF_CODE ASC;
