SELECT
    A.CODE CODE
    ,A.NAME NAME
    ,A.TOTAL_AMT TOTAL_AMT
FROM (
    SELECT
        I.ITEM_CODE CODE
        , I.ITEM_NAME NAME
        , SUM(D.UNITPRICE * D.ORDER_QTY) TOTAL_AMT
    FROM ORDERS_DTL D
    INNER JOIN ORDERS O
    ON D.ORDER_NO = O.ORDER_NO
    AND O.ORDER_DATE BETWEEN '2023-05-14' AND '2023-05-20'
    INNER JOIN ITEM I
    ON D.ITEM_CODE = I.ITEM_CODE
    GROUP BY I.ITEM_CODE,I.ITEM_NAME
    ORDER BY TOTAL_AMT DESC, CODE DESC
) A
LIMIT 5
;