DELETE
FROM ITEM
WHERE
STOCK_MANAGEMENT_TYPE = 1
AND (
NOT EXISTS (
    SELECT ITEM_CODE
    FROM STOCK S
    WHERE S.ITEM_CODE = ITEM.ITEM_CODE
)
OR
EXISTS (
    SELECT ITEM_CODE
    FROM STOCK S
    WHERE S.ITEM_CODE = ITEM.ITEM_CODE
    GROUP BY S.ITEM_CODE
    HAVING MAX(IFNULL(S.LAST_DELIVERY_DATE, '2100-01-01')) <= DATE('2023-06-01', '-6 months')
    AND SUM(S.ACTUAL_AMT) = 0
));